<script setup>
import { ref, onMounted } from 'vue'
import PostCard from './components/PostCard.vue'

const posts = ref([]);
const loading = ref(true);
const fetchError = ref(false);

// App.vue now only acts as a dumb client reading static local JSON.
// All heavy lifting (RSS fetching, NLP parsing, categorizing) is done by backend/fetcher.js
async function fetchLiveNews() {
    loading.value = true;
    fetchError.value = false;
    // Target the local static file generated by the backend fetcher
    const DATA_URL = '/data/news.json';

    try {
        // Add a cache buster timestamp so we always get the fresh file
        const response = await fetch(`${DATA_URL}?t=${new Date().getTime()}`);
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        posts.value = data;
    } catch (error) {
        console.error("Failed to load local intranet news data:", error);
        fetchError.value = true;
    } finally {
        loading.value = false;
    }
}

onMounted(() => {
    fetchLiveNews();
});
</script>

<template>
  <nav class="navbar">
    <div class="nav-container">
      <div class="logo">
        <i class="fa-solid fa-shield-halved"></i>
        <span>生活資安觀測站</span>
      </div>
      <div class="nav-links">
        <a href="#" class="active"><i class="fa-solid fa-house"></i> 首頁動態</a>
        <a href="#"><i class="fa-solid fa-fire"></i> 最新威脅</a>
        <a href="#"><i class="fa-solid fa-book-open"></i> 防護辭典</a>
      </div>
      <div class="user-profile">
        <div class="avatar-placeholder"><i class="fa-solid fa-user"></i></div>
      </div>
    </div>
  </nav>

  <main class="main-container">
    <aside class="sidebar left-sidebar">
      <div class="widget categories-widget">
        <h3>分類主題</h3>
        <ul>
          <li class="active"><i class="fa-solid fa-border-all"></i> 全部動態</li>
          <li><i class="fa-solid fa-mask"></i> 詐騙防範</li>
          <li><i class="fa-solid fa-key"></i> 密碼與帳號</li>
          <li><i class="fa-solid fa-wifi"></i> 網路與隱私</li>
          <li><i class="fa-solid fa-mobile-screen"></i> 手機安全</li>
        </ul>
      </div>
    </aside>

    <section class="feed">
      <div v-if="loading" id="loader" class="loader-container">
        <div class="spinner"></div>
        <p>正在努力為您抓取並轉譯最新的資安情報...</p>
      </div>

      <div v-else-if="fetchError" class="loader-container" style="color: var(--danger-color);">
        <i class="fa-solid fa-circle-exclamation" style="font-size: 2rem; margin-bottom: 1rem;"></i>
        <p>無法載入即時情報，網路連線可能異常。</p>
        <button @click="fetchLiveNews" style="margin-top: 1rem; padding: 0.5rem 1rem; cursor:pointer;">重新載入</button>
      </div>

      <PostCard v-else v-for="post in posts" :key="post.id" :post="post" />
    </section>

    <aside class="sidebar right-sidebar">
      <div class="widget alert-widget">
        <h3><i class="fa-solid fa-triangle-exclamation" style="color: #ff4757;"></i> 動態資料來源 (內網)</h3>
        <div class="alert-item" style="border-left-color: var(--accent-color); background-color: #f0fdf4;">
          <span class="badge" style="background-color: var(--accent-color); color: white; padding: 2px 6px; border-radius: 4px; font-size: 0.75rem;">封閉安全模式</span>
          <p>為了確保高規格資安，本網站在使用者端**完全斷網運行**。資料由後台排程獨立同步，前端無任何對外連線。</p>
        </div>
      </div>
    </aside>
  </main>
</template>
